# Generated by Django 4.1.5 on 2023-01-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart_item",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cart_item",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Cart_item",
        ),
    ]
